image_service/image_processing/urls.py
from django.urls import path

from . import views


app_name = 'processing'

urlpatterns = [
    path('', views.image_list, name='image_list'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('resize_image/<int:image_id>/', views.resize_image, name='resize_image'),
]

image_service/image_service/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_processing.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

image_service/image_processing/models.py
from django.db import models
from django.conf import settings


class Image(models.Model):
    image = models.ImageField(upload_to=settings.IMAGE_DIR)

image_service/image_processing/forms.py
from django import forms


class ImageLoadForm(forms.Form):
    image_url = forms.URLField(label='Ссылка', required=False)
    image_file = forms.ImageField(label='Файл', required=False)

    def clean(self):
        cleaned_data = super().clean()
        image_url = cleaned_data.get('image_url')
        image_file = cleaned_data.get('image_file')

        if image_url and image_file:
            raise forms.ValidationError(
                    'Нельзя отправлять сразу два изображения'
            )
        elif not image_url and not image_file:
            raise forms.ValidationError(
                    'Нужно загрузить изображение'
            )


class ImageResizeForm(forms.Form):
    width = forms.IntegerField(min_value=1,
                               label='Ширина',
                               required=False)
    height = forms.IntegerField(min_value=1,
                                label='Высота',
                                required=False)

    def clean(self):
        cleaned_data = super().clean()
        width = cleaned_data.get('width')
        height = cleaned_data.get('height')

        if not width and not height:
            raise forms.ValidationError(
                    'Нужно задать хотя бы один параметр'
            )

image_service/image_processing/views.py
from django.shortcuts import render, redirect

from .forms import ImageLoadForm, ImageResizeForm
from .models import Image
from . import services


def image_list(request):
    images = services.get_all_images()
    imgs = {img.image.name.split('/')[-1]: img for img in images}
    return render(request, 'image_list.html', {'images': imgs})


def upload_image(request):
    if request.method == 'POST':
        form = ImageLoadForm(request.POST, request.FILES)
        if form.is_valid():
            image_file = form.cleaned_data.get('image_file', None)
            image_url = form.cleaned_data.get('image_url', None)
            if image_file:
                image = services.save_image_by_file(image_file)
            else:
                image = services.save_image_by_url(image_url)
            return redirect('processing:resize_image', image_id=image.id)
    else:
        form = ImageLoadForm()
    return render(request, 'upload_image.html', {'form': form})


def resize_image(request, image_id: int):
    image = Image.objects.filter(id=image_id).first()
    image_name = image.image.name.split('/')[-1]

    if request.method == 'POST':
        form = ImageResizeForm(request.POST)
        if form.is_valid():
            width = form.cleaned_data['width']
            height = form.cleaned_data['height']
            image = services.resize_image(image, width, height)
    else:
        form = ImageResizeForm()

    context = {
        'form': form,
        'image_name': image_name,
        'image': image,
    }

    return render(request, 'resize_image.html', context)

image_service/image_processing/templates/image_list.html
<!doctype html>

<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>Список изображений</title>
</head>

<body>
    <h1>Список изображений</h1>
    {% if not images %}
        <p>
        Нет доступных изображений
        <p>
    {% endif %}
    {% for img_name, img in images.items %}
        <a href="{% url 'processing:resize_image' img.id %}">{{ img_name }}</a>
        <p>
    {% endfor %}
    <p>
    <a href="{% url 'processing:upload_image' %}">Добавить изображение</a>
</body>

</html>

image_service/image_processing/templates/resize_image.html
<!doctype html>

<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>Загрузить изображение</title>
</head>

<body>
    <a href="{% url 'processing:image_list' %}">Назад к списку</a>
    <p>
    <h1>{{ image_name }}</h1>
    <form action="" method="post" enctype=multipart/form-data>
        {% csrf_token %}
        {% for fld in form %}
            {{ fld.label }} <p>
            {{ fld }} {{ fld.error }} <p>
        {% endfor %}
        {% for error in form.non_field_errors %}
            <strong>{{ error|escape }}</strong>
        {% endfor %}
        <p>
        <button type="submit">Отправить</button>
    </form>
    <p>
    <img src="{{ image.image.url }}" alt="connect">
</body>

</html>

image_service/image_processing/templates/upload_image.html
<!doctype html>

<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>Загрузить изображение</title>
</head>

<body>
    <a href="{% url 'processing:image_list' %}">Назад к списку</a>
    <p>
    <h1>Новое изображение</h1>
    <p>
    <form action="" method="post" enctype=multipart/form-data>
        {% csrf_token %}
        {% for fld in form %}
            {{ fld.label }} <p>
            {{ fld }} {{ fld.error }} <p>
        {% endfor %}
        {% for error in form.non_field_errors %}
            <strong>{{ error|escape }}</strong>
        {% endfor %}
        <p>
        <button type="submit">Отправить</button>
    </form>
    <p>

</body>

</html>